// Curated brand list for Brandle puzzles.
// Brand names should be alphabetic only (letters A-Z). No spaces, digits, or punctuation.
// Length range: 4 to 9 letters keeps the grid readable on mobile.

export type Brand = {
  name: string; // uppercase, letters only
  category: string; // for hints / future filtering
  fact?: string; // optional one-liner shown after solve
};

export const BRANDS: Brand[] = [
  // 4 letters
  { name: "ACER", category: "Technology" },
  { name: "ALDI", category: "Retail" },
  { name: "AMUL", category: "Food" },
  { name: "ASUS", category: "Technology" },
  { name: "AUDI", category: "Automotive" },
  { name: "AVON", category: "Beauty" },
  { name: "BOSE", category: "Electronics" },
  { name: "DELL", category: "Technology" },
  { name: "DIDI", category: "Transport" },
  { name: "DOVE", category: "Personal Care" },
  { name: "EBAY", category: "Internet" },
  { name: "ESPN", category: "Media" },
  { name: "ETSY", category: "Internet" },
  { name: "FILA", category: "Apparel" },
  { name: "FORD", category: "Automotive" },
  { name: "FUJI", category: "Photography" },
  { name: "HSBC", category: "Finance" },
  { name: "HULU", category: "Media" },
  { name: "IKEA", category: "Retail" },
  { name: "LEGO", category: "Toys", fact: "From the Danish phrase leg godt, meaning play well." },
  { name: "LYFT", category: "Transport" },
  { name: "MINI", category: "Automotive" },
  { name: "NIKE", category: "Apparel", fact: "Named after the Greek goddess of victory." },
  { name: "OLAY", category: "Beauty" },
  { name: "OPPO", category: "Electronics" },
  { name: "OREO", category: "Food" },
  { name: "PUMA", category: "Apparel" },
  { name: "ROKU", category: "Media" },
  { name: "SONY", category: "Electronics", fact: "Its name combines sound-related Latin with the 1950s slang sonny." },
  { name: "TIVO", category: "Media" },
  { name: "UBER", category: "Transport" },
  { name: "VANS", category: "Apparel" },
  { name: "VISA", category: "Finance" },
  { name: "XERO", category: "Technology" },
  { name: "ZARA", category: "Fashion" },
  { name: "ZOHO", category: "Technology" },

  // 5 letters
  { name: "ADOBE", category: "Technology", fact: "Named after Adobe Creek near cofounder John Warnock's home." },
  { name: "APPLE", category: "Technology", fact: "Steve Jobs chose the name after visiting an apple farm." },
  { name: "ATARI", category: "Gaming" },
  { name: "CANON", category: "Electronics" },
  { name: "CANVA", category: "Technology", fact: "Started in Australia as an easier way to create visual designs." },
  { name: "CHIME", category: "Finance" },
  { name: "COACH", category: "Fashion" },
  { name: "COORS", category: "Beverage" },
  { name: "DYSON", category: "Consumer Goods", fact: "James Dyson built thousands of prototypes before launching his vacuum." },
  { name: "EPSON", category: "Electronics" },
  { name: "FEDEX", category: "Logistics", fact: "Its logo hides an arrow between the E and x." },
  { name: "FENDI", category: "Fashion" },
  { name: "GOPRO", category: "Electronics" },
  { name: "GUCCI", category: "Fashion" },
  { name: "HERTZ", category: "Transport" },
  { name: "HONDA", category: "Automotive" },
  { name: "INTEL", category: "Technology" },
  { name: "JUICY", category: "Fashion" },
  { name: "KENZO", category: "Fashion" },
  { name: "BOSCH", category: "Industrial" },
  { name: "KODAK", category: "Photography" },
  { name: "LEXUS", category: "Automotive" },
  { name: "LOTUS", category: "Automotive" },
  { name: "LOTTE", category: "Food" },
  { name: "MANGO", category: "Fashion" },
  { name: "MAZDA", category: "Automotive" },
  { name: "NIVEA", category: "Beauty" },
  { name: "NOKIA", category: "Technology" },
  { name: "PEPSI", category: "Beverage" },
  { name: "PIXAR", category: "Media" },
  { name: "PRADA", category: "Fashion" },
  { name: "RICOH", category: "Electronics" },
  { name: "ROLEX", category: "Luxury", fact: "The name was designed to be short and easy to pronounce globally." },
  { name: "SHEIN", category: "Fashion" },
  { name: "SHELL", category: "Energy" },
  { name: "SHURE", category: "Electronics" },
  { name: "SKYPE", category: "Technology" },
  { name: "SLACK", category: "Technology" },
  { name: "SONIC", category: "Food" },
  { name: "SONOS", category: "Electronics" },
  { name: "TESLA", category: "Automotive" },
  { name: "TIDAL", category: "Media" },
  { name: "VALVE", category: "Gaming" },
  { name: "VIZIO", category: "Electronics" },
  { name: "VOLVO", category: "Automotive" },
  { name: "XEROX", category: "Technology" },

  // 6 letters
  { name: "ADIDAS", category: "Apparel", fact: "Named after founder Adolf Adi Dassler." },
  { name: "AIRBNB", category: "Hospitality", fact: "The original idea involved renting air mattresses during a design conference." },
  { name: "AIRBUS", category: "Aerospace" },
  { name: "AMAZON", category: "Internet", fact: "Named after the Amazon River to suggest massive scale." },
  { name: "ARMANI", category: "Fashion" },
  { name: "BARBIE", category: "Toys" },
  { name: "BOEING", category: "Aerospace" },
  { name: "CHANEL", category: "Fashion" },
  { name: "CLOROX", category: "Consumer Goods" },
  { name: "COSTCO", category: "Retail" },
  { name: "DISNEY", category: "Media", fact: "Founded by brothers Walt and Roy Disney in 1923." },
  { name: "FOSSIL", category: "Fashion" },
  { name: "GARMIN", category: "Electronics" },
  { name: "GITHUB", category: "Technology", fact: "Its mascot is the Octocat." },
  { name: "GITLAB", category: "Technology" },
  { name: "GOOGLE", category: "Technology", fact: "A misspelling of googol, the number 10^100." },
  { name: "HERMES", category: "Fashion" },
  { name: "HILTON", category: "Hospitality" },
  { name: "HUAWEI", category: "Electronics" },
  { name: "JAGUAR", category: "Automotive" },
  { name: "KERING", category: "Fashion" },
  { name: "KINDER", category: "Food" },
  { name: "LENOVO", category: "Technology" },
  { name: "MAKITA", category: "Industrial" },
  { name: "MATTEL", category: "Toys" },
  { name: "NESTLE", category: "Food" },
  { name: "NISSAN", category: "Automotive" },
  { name: "NOTION", category: "Technology" },
  { name: "OAKLEY", category: "Eyewear" },
  { name: "ORACLE", category: "Technology", fact: "Its name came from a CIA database project codename." },
  { name: "PANERA", category: "Food" },
  { name: "PAYPAL", category: "Finance", fact: "It started as a way to beam payments between PalmPilots." },
  { name: "PFIZER", category: "Pharma" },
  { name: "RAYBAN", category: "Eyewear" },
  { name: "REEBOK", category: "Apparel" },
  { name: "REVLON", category: "Beauty" },
  { name: "RIMOWA", category: "Travel" },
  { name: "RIVIAN", category: "Automotive" },
  { name: "SHAZAM", category: "Media" },
  { name: "SHOPEE", category: "Retail" },
  { name: "SPRINT", category: "Telecom" },
  { name: "STRIPE", category: "Finance", fact: "The Collison brothers built it to make online payments easier for developers." },
  { name: "SUBARU", category: "Automotive" },
  { name: "SUBWAY", category: "Food" },
  { name: "SUZUKI", category: "Automotive" },
  { name: "TARGET", category: "Retail" },
  { name: "TIKTOK", category: "Media" },
  { name: "TINDER", category: "Internet" },
  { name: "TOYOTA", category: "Automotive", fact: "The name was changed from Toyoda because Toyota took eight brush strokes in Japanese." },
  { name: "TRELLO", category: "Technology" },
  { name: "TUMBLR", category: "Internet" },
  { name: "UNIQLO", category: "Fashion" },
  { name: "WECHAT", category: "Technology" },
  { name: "XIAOMI", category: "Electronics" },
  { name: "ZENITH", category: "Luxury" },
  { name: "ZOMATO", category: "Food" },

  // 7 letters
  { name: "ALIBABA", category: "Internet" },
  { name: "BENTLEY", category: "Automotive" },
  { name: "BINANCE", category: "Finance" },
  { name: "BITCOIN", category: "Finance" },
  { name: "BUGATTI", category: "Automotive" },
  { name: "CARTIER", category: "Luxury" },
  { name: "CHOBANI", category: "Food" },
  { name: "CLARINS", category: "Beauty" },
  { name: "DISCORD", category: "Technology", fact: "It grew from tools built for gamers to coordinate while playing." },
  { name: "DORITOS", category: "Food" },
  { name: "DROPBOX", category: "Technology" },
  { name: "EXPEDIA", category: "Travel" },
  { name: "FERRARI", category: "Automotive" },
  { name: "FERRERO", category: "Food" },
  { name: "GARNIER", category: "Beauty" },
  { name: "HERSHEY", category: "Food" },
  { name: "HYUNDAI", category: "Automotive" },
  { name: "JACUZZI", category: "Consumer Goods" },
  { name: "KELLOGG", category: "Food" },
  { name: "LACOSTE", category: "Fashion" },
  { name: "MIRINDA", category: "Beverage" },
  { name: "NETFLIX", category: "Media", fact: "It began as a DVD-by-mail service before streaming." },
  { name: "PAMPERS", category: "Personal Care" },
  { name: "PANDORA", category: "Jewelry" },
  { name: "PERRIER", category: "Beverage" },
  { name: "PHILIPS", category: "Electronics" },
  { name: "PIONEER", category: "Electronics" },
  { name: "PORSCHE", category: "Automotive" },
  { name: "RAKUTEN", category: "Internet" },
  { name: "RITUALS", category: "Beauty" },
  { name: "RYANAIR", category: "Airlines" },
  { name: "SAMSUNG", category: "Electronics" },
  { name: "SHOPIFY", category: "Technology", fact: "It grew out of an online snowboard shop." },
  { name: "SIEMENS", category: "Industrial" },
  { name: "SPOTIFY", category: "Media" },
  { name: "TOSHIBA", category: "Electronics" },
  { name: "TWITTER", category: "Internet" },
  { name: "VERIZON", category: "Telecom" },

  // 8 letters
  { name: "BANDCAMP", category: "Media" },
  { name: "BARCLAYS", category: "Finance" },
  { name: "BROADCOM", category: "Technology" },
  { name: "BURBERRY", category: "Fashion" },
  { name: "CITIBANK", category: "Finance" },
  { name: "COINBASE", category: "Finance" },
  { name: "DELOITTE", category: "Consulting" },
  { name: "DISCOVER", category: "Finance" },
  { name: "DOORDASH", category: "Food" },
  { name: "EMIRATES", category: "Airlines" },
  { name: "EVERNOTE", category: "Technology" },
  { name: "FACEBOOK", category: "Internet", fact: "It launched first for Harvard students in 2004." },
  { name: "FANDANGO", category: "Media" },
  { name: "GILLETTE", category: "Personal Care" },
  { name: "HALLMARK", category: "Consumer Goods" },
  { name: "HEINEKEN", category: "Beverage" },
  { name: "LINKEDIN", category: "Internet", fact: "It launched in 2003, before many later social networks." },
  { name: "MARLBORO", category: "Tobacco" },
  { name: "MARRIOTT", category: "Hospitality" },
  { name: "MERCEDES", category: "Automotive" },
  { name: "MONDELEZ", category: "Food" },
  { name: "MOTOROLA", category: "Electronics" },
  { name: "NINTENDO", category: "Gaming", fact: "It started in 1889 as a playing card company." },
  { name: "QUALCOMM", category: "Technology" },
  { name: "RABOBANK", category: "Finance" },
  { name: "REYNOLDS", category: "Consumer Goods" },
  { name: "SKECHERS", category: "Apparel" },
  { name: "SNAPCHAT", category: "Internet", fact: "It was originally called Picaboo." },
  { name: "SOFTBANK", category: "Telecom" },
  { name: "STARLINK", category: "Telecom" },
  { name: "TELEGRAM", category: "Technology" },
  { name: "UNILEVER", category: "Consumer Goods" },
  { name: "VODAFONE", category: "Telecom" },
  { name: "WHATSAPP", category: "Technology" },

  // 9 letters
  { name: "ACCENTURE", category: "Consulting", fact: "The name comes from accent on the future." },
  { name: "ANTHROPIC", category: "Technology" },
  { name: "BLACKROCK", category: "Finance" },
  { name: "BLOOMBERG", category: "Media" },
  { name: "CARREFOUR", category: "Retail" },
  { name: "CHEVROLET", category: "Automotive" },
  { name: "FERRAGAMO", category: "Fashion" },
  { name: "GRAMMARLY", category: "Technology" },
  { name: "HONEYWELL", category: "Industrial" },
  { name: "HOOTSUITE", category: "Technology" },
  { name: "INSTAGRAM", category: "Internet" },
  { name: "LULULEMON", category: "Apparel" },
  { name: "MAILCHIMP", category: "Technology" },
  { name: "MICROSOFT", category: "Technology", fact: "The name blends microcomputer and software." },
  { name: "NORDSTROM", category: "Retail" },
  { name: "OVERSTOCK", category: "Retail" },
  { name: "PANASONIC", category: "Electronics" },
  { name: "PARAMOUNT", category: "Media" },
  { name: "ROBINHOOD", category: "Finance" },
  { name: "SANTANDER", category: "Finance" },
  { name: "STARBUCKS", category: "Food", fact: "Named after the first mate in Moby Dick." },
  { name: "WALGREENS", category: "Retail" },
  { name: "WORDPRESS", category: "Technology" },
];

// Filter to clean alphabetic 4–9, deduped.
const CLEAN: Brand[] = (() => {
  const seen = new Set<string>();
  const out: Brand[] = [];
  for (const b of BRANDS) {
    const name = b.name.toUpperCase();
    if (!/^[A-Z]+$/.test(name)) continue;
    if (name.length < 4 || name.length > 9) continue;
    if (seen.has(name)) continue;
    seen.add(name);
    out.push({ name, category: b.category, fact: b.fact });
  }
  return out;
})();

export const PUZZLE_BRANDS = CLEAN;
