// Curated brand list for Brandle puzzles.
// Brand names should be alphabetic only (letters A-Z). No spaces, digits, or punctuation.
// Length range: 4 to 9 letters keeps the grid readable on mobile.

export type Brand = {
  name: string; // uppercase, letters only
  category: string; // for hints / future filtering
  fact?: string; // optional one-liner shown after solve
};

export const BRANDS: Brand[] = [
  // 4 letters
  { name: "ACER", category: "Technology", fact: "Named from the Latin word for sharp, referring to precision engineering." },
  { name: "ALDI", category: "Retail", fact: "Short for Albrecht Diskont, the discount store founded by brothers Karl and Theo Albrecht." },
  { name: "AMUL", category: "Food", fact: "An acronym for Anand Milk Union Limited, a Gujarat cooperative founded in 1946." },
  { name: "ASUS", category: "Technology", fact: "Named after Pegasus, the winged horse of Greek mythology." },
  { name: "AUDI", category: "Automotive", fact: "A Latin translation of the founder's surname: Horch means to listen in German." },
  { name: "AVON", category: "Beauty", fact: "Named after the River Avon near Shakespeare's birthplace, chosen by founder David McConnell." },
  { name: "BOSE", category: "Electronics", fact: "Founded by MIT professor Amar Bose after he was disappointed by a high-end stereo he bought." },
  { name: "DELL", category: "Technology", fact: "Founded in a University of Texas dorm room by Michael Dell in 1984." },
  { name: "DIDI", category: "Ride-Hailing", fact: "Means hailing a taxi in Mandarin." },
  { name: "DOVE", category: "Personal Care", fact: "The name was chosen to evoke mildness and purity when it launched in 1957." },
  { name: "EBAY", category: "Internet", fact: "Originally called AuctionWeb; eBay was just the domain name Pierre Omidyar wanted." },
  { name: "ESPN", category: "Media", fact: "Stands for Entertainment and Sports Programming Network, launched in 1979." },
  { name: "ETSY", category: "Internet", fact: "The founder claims it was a nonsense word heard in an Italian film." },
  { name: "FILA", category: "Apparel", fact: "Founded in 1911 in the Italian Alps as a textile company." },
  { name: "FORD", category: "Automotive", fact: "Henry Ford launched the Model T in 1908, making cars affordable for ordinary workers." },
  { name: "FUJI", category: "Photography", fact: "Named after Mount Fuji, Japan's most iconic mountain." },
  { name: "HSBC", category: "Finance", fact: "Stands for Hongkong and Shanghai Banking Corporation, founded in 1865." },
  { name: "HULU", category: "Media", fact: "A Mandarin word meaning interactive recording or gourd, a vessel for precious things." },
  { name: "IKEA", category: "Retail", fact: "An acronym: Ingvar Kamprad, Elmtaryd farm, Agunnaryd village — the founder's initials and hometown." },
  { name: "LEGO", category: "Toys", fact: "From the Danish phrase leg godt, meaning play well." },
  { name: "LYFT", category: "Ride-Hailing", fact: "The pink moustaches on early Lyft cars became the brand's defining early image." },
  { name: "MINI", category: "Automotive", fact: "Launched in 1959 by Alec Issigonis to be the most space-efficient small car ever made." },
  { name: "NIKE", category: "Apparel", fact: "Named after the Greek goddess of victory." },
  { name: "OLAY", category: "Beauty", fact: "Originally called Oil of Olay; the name Ulay was used in some markets to avoid the word oil." },
  { name: "OPPO", category: "Electronics", fact: "Founded in 2004 in Dongguan, China; grew from MP3 players to smartphones." },
  { name: "OREO", category: "Food", fact: "The origin of the name is unknown even internally; theories range from French or for gold." },
  { name: "PUMA", category: "Apparel", fact: "Rudolf Dassler founded Puma after a split with his brother Adi, who went on to found Adidas." },
  { name: "ROKU", category: "Media", fact: "Means six in Japanese — it was Anthony Wood's sixth company." },
  { name: "SONY", category: "Electronics", fact: "Its name combines sound-related Latin with the 1950s slang sonny." },
  { name: "TIVO", category: "Streaming", fact: "Its DVR made pausing live television a mainstream feature after launching in 1999." },
  { name: "UBER", category: "Ride-Hailing", fact: "Originally called UberCab; it shortened the name after taxi regulators objected." },
  { name: "VANS", category: "Apparel", fact: "Founded in 1966 in Anaheim, California; initially sold direct from the factory on day one." },
  { name: "VISA", category: "Finance", fact: "The name was chosen because it is recognisable in every language." },
  { name: "XERO", category: "Technology", fact: "The zero in the name refers to paperwork — as in zero paperwork for accounting." },
  { name: "ZARA", category: "Fashion", fact: "Founder Amancio Ortega originally wanted to call it Zorba but the name was taken." },
  { name: "ZOHO", category: "Technology", fact: "Originally AdventNet; renamed Zoho in 2009 after its flagship product." },

  // 5 letters
  { name: "ADOBE", category: "Technology", fact: "Named after Adobe Creek near cofounder John Warnock's home." },
  { name: "APPLE", category: "Technology", fact: "Steve Jobs chose the name after visiting an apple farm." },
  { name: "ATARI", category: "Gaming", fact: "A term from the board game Go meaning your opponent's pieces are about to be captured." },
  { name: "CANON", category: "Electronics", fact: "Originally Kwanon, named after the Buddhist goddess of mercy; changed for global markets." },
  { name: "CANVA", category: "Technology", fact: "Started in Australia as an easier way to create visual designs." },
  { name: "CHIME", category: "Finance", fact: "Launched in 2013 as a no-fee digital bank aimed at paycheck-to-paycheck Americans." },
  { name: "COACH", category: "Fashion", fact: "Founded in a Manhattan loft in 1941, originally making wallets and billfolds by hand." },
  { name: "COORS", category: "Beverage", fact: "Adolph Coors started the brewery in Golden, Colorado in 1873 using Rocky Mountain spring water." },
  { name: "DYSON", category: "Consumer Goods", fact: "James Dyson built thousands of prototypes before launching his vacuum." },
  { name: "EPSON", category: "Electronics", fact: "Stands for Son of EP — EP being the name of the first electronic printer it launched." },
  { name: "FEDEX", category: "Logistics", fact: "Its logo hides an arrow between the E and x." },
  { name: "FENDI", category: "Fashion", fact: "Founded in Rome in 1925 as a fur and leather shop by Adele and Edoardo Fendi." },
  { name: "GOPRO", category: "Electronics", fact: "The name came from founder Nick Woodman wanting a camera he could use surfing Go Pro." },
  { name: "GUCCI", category: "Fashion", fact: "Guccio Gucci was inspired by the fine luggage he saw wealthy guests carrying as a hotel porter." },
  { name: "HERTZ", category: "Car Rental", fact: "Named after founder John Hertz, who started the company in 1918 with just 12 cars." },
  { name: "HONDA", category: "Automotive", fact: "Soichiro Honda began by making piston rings in his garage in 1937." },
  { name: "INTEL", category: "Technology", fact: "Short for Integrated Electronics, the name was nearly bought by a motel chain." },
  { name: "JUICY", category: "Fashion", fact: "Juicy Couture's founders originally sold maternity pants before pivoting to velour tracksuits." },
  { name: "KENZO", category: "Fashion", fact: "Founded in Paris in 1970 by Japanese designer Kenzo Takada, who arrived with no French." },
  { name: "BOSCH", category: "Industrial", fact: "Robert Bosch founded the company in Stuttgart in 1886 in a back-room workshop." },
  { name: "KODAK", category: "Photography", fact: "George Eastman invented the name — he loved the letter K and wanted a word starting and ending with it." },
  { name: "LEXUS", category: "Automotive", fact: "Toyota developed the name through an exhaustive branding exercise in the late 1980s." },
  { name: "LOTUS", category: "Automotive", fact: "Founder Colin Chapman built his first car from a used Austin Seven in a lock-up garage." },
  { name: "LOTTE", category: "Food", fact: "Founded in Japan in 1948 by Korean entrepreneur Shin Kyuk-ho, named after the heroine of Werther." },
  { name: "MANGO", category: "Fashion", fact: "The Spanish founders named it after eating a mango in the Philippines in 1984." },
  { name: "MAZDA", category: "Automotive", fact: "Named after Ahura Mazda, the Zoroastrian god of wisdom, also related to founder Jujiro Matsuda." },
  { name: "NIVEA", category: "Beauty", fact: "Named from the Latin niveus, meaning snow-white, for the colour of its original cream." },
  { name: "NOKIA", category: "Technology", fact: "Originally a wood-pulp mill on the Nokia River in Finland, founded in 1865." },
  { name: "PEPSI", category: "Beverage", fact: "Named after pepsin, the digestive enzyme, and kola nuts used in the original recipe." },
  { name: "PIXAR", category: "Media", fact: "The name was coined to sound like a made-up computer term combining pixel and the Spanish ar." },
  { name: "PRADA", category: "Fashion", fact: "Mario Prada founded the company in Milan in 1913 as a leather goods shop." },
  { name: "RICOH", category: "Electronics", fact: "Stands for Riken Kankoshi Company; started making sensitised paper in Tokyo in 1936." },
  { name: "ROLEX", category: "Watches", fact: "The name was designed to be short and easy to pronounce globally." },
  { name: "SHEIN", category: "Fashion", fact: "Started in China in 2008 as SheInside before shortening its name to SHEIN." },
  { name: "SHELL", category: "Energy", fact: "The company started in the 1830s selling exotic shells imported from the Far East." },
  { name: "SHURE", category: "Electronics", fact: "Sidney Shure started the company in Chicago in 1925 selling radio parts by mail." },
  { name: "SKYPE", category: "Technology", fact: "Derived from Sky Peer-to-Peer, shortened and altered for branding." },
  { name: "SLACK", category: "Technology", fact: "Originally a backronym: Searchable Log of All Conversation and Knowledge." },
  { name: "SONIC", category: "Food", fact: "The name plays on sound and speed — the chain opened in 1953 as a drive-in." },
  { name: "SONOS", category: "Electronics", fact: "From the Latin for sound; founded in Santa Barbara in 2002 to make whole-home audio simple." },
  { name: "TESLA", category: "Automotive", fact: "Named after Nikola Tesla, the inventor of the AC electric motor that powers EVs." },
  { name: "TIDAL", category: "Music", fact: "The streaming service was acquired and relaunched by Jay-Z in 2015 as an artist-owned platform." },
  { name: "VALVE", category: "Gaming", fact: "Founded in 1996 by ex-Microsoft employees Gabe Newell and Mike Harrington." },
  { name: "VIZIO", category: "Electronics", fact: "Founded in 2002 to bring flat-screen TVs to mass-market prices; the V stands for vision." },
  { name: "VOLVO", category: "Automotive", fact: "Latin for I roll — fittingly chosen for a car company in 1927." },
  { name: "XEROX", category: "Technology", fact: "Derived from the Greek word for dry — referring to the dry-ink copying process it invented." },

  // 6 letters
  { name: "ADIDAS", category: "Apparel", fact: "Named after founder Adolf Adi Dassler." },
  { name: "AIRBNB", category: "Hospitality", fact: "The original idea involved renting air mattresses during a design conference." },
  { name: "AIRBUS", category: "Aerospace", fact: "Launched in 1969 as a European consortium to challenge Boeing's dominance." },
  { name: "AMAZON", category: "Internet", fact: "Named after the Amazon River to suggest massive scale." },
  { name: "ARMANI", category: "Fashion", fact: "Giorgio Armani launched the brand in 1975 after being fired from Nino Cerruti." },
  { name: "BARBIE", category: "Toys", fact: "Named after Barbara Handler, daughter of Mattel co-founder Ruth Handler, launched in 1959." },
  { name: "BOEING", category: "Aerospace", fact: "William Boeing built his first aircraft in a boathouse on Seattle's Lake Union in 1916." },
  { name: "CHANEL", category: "Fashion", fact: "Coco Chanel opened her first shop in 1910 selling hats, and liberated women from the corset era." },
  { name: "CLOROX", category: "Cleaning", fact: "Launched in 1913 as the first liquid bleach made from Oakland's salt-water brine." },
  { name: "COSTCO", category: "Retail", fact: "The first Costco opened in Seattle in 1983; it sold only to small businesses initially." },
  { name: "DISNEY", category: "Media", fact: "Founded by brothers Walt and Roy Disney in 1923." },
  { name: "FOSSIL", category: "Fashion", fact: "Founded in 1984 by brothers Tom and Kosta Kartsotis; the word fossil evoked American nostalgia." },
  { name: "GARMIN", category: "Electronics", fact: "Named after founders Gary Burrell and Min Kao; built GPS devices for aviation first." },
  { name: "GITHUB", category: "Technology", fact: "Its mascot is the Octocat." },
  { name: "GITLAB", category: "Technology", fact: "Started as a single Ruby script by a Ukrainian developer in 2011." },
  { name: "GOOGLE", category: "Technology", fact: "A misspelling of googol, the number 10^100." },
  { name: "HERMES", category: "Luxury Fashion", fact: "Founded in Paris in 1837 by Thierry Hermès as a harness workshop for European nobility." },
  { name: "HILTON", category: "Hospitality", fact: "Conrad Hilton bought his first hotel in Cisco, Texas, in 1919 after a bank deal fell through." },
  { name: "HUAWEI", category: "Electronics", fact: "The name means China is able or splendid achievement in Mandarin." },
  { name: "JAGUAR", category: "Automotive", fact: "Originally the Swallow Sidecar Company; renamed Jaguar in 1945 after the SS initials became problematic." },
  { name: "KERING", category: "Fashion", fact: "Originally Pinault-Printemps-Redoute; renamed Kering in 2013, from the Breton word for home." },
  { name: "KINDER", category: "Food", fact: "Italian for children, the Kinder brand was launched by Ferrero in 1968." },
  { name: "LENOVO", category: "Technology", fact: "A blend of Le from Legend (the company's previous name) and novo from the Latin for new." },
  { name: "MAKITA", category: "Industrial", fact: "Founded in Nagoya, Japan, in 1915 as an electric motor repair shop." },
  { name: "MATTEL", category: "Toys", fact: "Named from the founders' names: Harold Matson and Elliot Handler." },
  { name: "NESTLE", category: "Food", fact: "Henri Nestlé invented a milk-based baby food in Switzerland in 1867, saving an infant's life." },
  { name: "NISSAN", category: "Automotive", fact: "Abbreviated from Nippon Sangyo, meaning Japan Industries, founded in 1928." },
  { name: "NOTION", category: "Technology", fact: "Launched in 2016 after two years of rebuilding from scratch in Kyoto, Japan." },
  { name: "OAKLEY", category: "Eyewear", fact: "Jim Jannard founded Oakley in 1975, starting with motorcycle handlebar grips, not eyewear." },
  { name: "ORACLE", category: "Technology", fact: "Its name came from a CIA database project codename." },
  { name: "PANERA", category: "Food", fact: "Derived from the Spanish word for breadbasket, reflecting its bakery-café roots." },
  { name: "PAYPAL", category: "Finance", fact: "It started as a way to beam payments between PalmPilots." },
  { name: "PFIZER", category: "Pharma", fact: "Founded in Brooklyn in 1849 by cousins Charles Pfizer and Charles Erhart." },
  { name: "RAYBAN", category: "Eyewear", fact: "Originally developed in 1936 for the US Army Air Corps to reduce glare for pilots." },
  { name: "REEBOK", category: "Apparel", fact: "Named after the rhebok, a fast African antelope." },
  { name: "REVLON", category: "Beauty", fact: "Charles Revson and a chemist named Lachman founded it; the L became an N to give Revlon." },
  { name: "RIMOWA", category: "Luggage", fact: "Founded in Cologne in 1898; the grooved aluminium suitcase design debuted in 1950." },
  { name: "RIVIAN", category: "Automotive", fact: "The name comes from the Indian River, which runs near the Florida hometown of founder RJ Scaringe." },
  { name: "SHAZAM", category: "Music", fact: "Named after the magical word that transforms Billy Batson into Captain Marvel in DC Comics." },
  { name: "SHOPEE", category: "Retail", fact: "Launched in 2015 by Sea Limited in Singapore as a mobile-first marketplace for Southeast Asia." },
  { name: "SPRINT", category: "Telecom", fact: "Started in 1899 as a Kansas telephone company; the Sprint brand emerged in the 1980s." },
  { name: "STRIPE", category: "Finance", fact: "The Collison brothers built it to make online payments easier for developers." },
  { name: "SUBARU", category: "Automotive", fact: "The Japanese word for the Pleiades star cluster, which appears on the brand's logo." },
  { name: "SUBWAY", category: "Food", fact: "Started in 1965 with a ,,000 loan from a family friend in Bridgeport, Connecticut." },
  { name: "SUZUKI", category: "Automotive", fact: "Michio Suzuki built the company on power looms before pivoting to motorcycles in the 1950s." },
  { name: "TARGET", category: "Retail", fact: "The bullseye logo was chosen in 1962 to communicate precision, value, and bold aspiration." },
  { name: "TIKTOK", category: "Media", fact: "The app launched internationally in 2017 after ByteDance acquired Musical.ly." },
  { name: "TINDER", category: "Internet", fact: "Swiping right as a metaphor for attraction was pioneered at USC and launched in 2012." },
  { name: "TOYOTA", category: "Automotive", fact: "The name was changed from Toyoda because Toyota took eight brush strokes in Japanese." },
  { name: "TRELLO", category: "Technology", fact: "Started as a side project inside Fog Creek Software, spun out and acquired by Atlassian in 2017." },
  { name: "TUMBLR", category: "Internet", fact: "David Karp built the first version in two weeks and launched it in 2007 at age 20." },
  { name: "UNIQLO", category: "Fashion", fact: "Short for Unique Clothing Warehouse; the name came from a typo when registering in Hong Kong." },
  { name: "WECHAT", category: "Technology", fact: "Launched by Tencent in 2011, it reached 100 million users in 433 days." },
  { name: "XIAOMI", category: "Electronics", fact: "Means millet in Mandarin — founder Lei Jun chose it to convey humble, grain-level simplicity." },
  { name: "ZENITH", category: "Watches", fact: "Named to reflect peak craftsmanship; the brand adopted the slogan The stars will be your guide." },
  { name: "ZOMATO", category: "Food", fact: "Originally Foodiebay, renamed Zomato in 2010 — a made-up word that was easy to trademark." },

  // 7 letters
  { name: "ALIBABA", category: "Internet", fact: "Jack Ma chose the name in a San Francisco café after checking that people around the world recognised it." },
  { name: "BENTLEY", category: "Automotive", fact: "Walter Owen Bentley built his first car engine from aluminium alloy in a tiny London workshop in 1919." },
  { name: "BINANCE", category: "Finance", fact: "A portmanteau of binary and finance, launched by Changpeng Zhao in 2017." },
  { name: "BITCOIN", category: "Finance", fact: "The whitepaper was published pseudonymously under the name Satoshi Nakamoto in 2008." },
  { name: "BUGATTI", category: "Automotive", fact: "Ettore Bugatti started the company in Alsace in 1909; his cars won more Grand Prix than any other early marque." },
  { name: "CARTIER", category: "Jewellery", fact: "Louis-François Cartier took over his master's jewellery workshop in Paris in 1847." },
  { name: "CHOBANI", category: "Food", fact: "Founder Hamdi Ulukaya bought a shuttered Kraft yoghurt plant in upstate New York with an SBA loan." },
  { name: "CLARINS", category: "Beauty", fact: "Founded in Paris in 1954 by Jacques Courtin-Clarins, who began by offering free treatments to clients." },
  { name: "DISCORD", category: "Technology", fact: "It grew from tools built for gamers to coordinate while playing." },
  { name: "DORITOS", category: "Food", fact: "Invented at Disneyland's Casa de Fritos restaurant from stale leftover tortillas in 1964." },
  { name: "DROPBOX", category: "Technology", fact: "Drew Houston built the first prototype after forgetting his USB drive on a bus." },
  { name: "EXPEDIA", category: "Travel", fact: "Launched in 1996 as a division of Microsoft before being spun off as an independent company." },
  { name: "FERRARI", category: "Automotive", fact: "Enzo Ferrari founded the racing team before the road-car company; he called production cars a necessary evil." },
  { name: "FERRERO", category: "Food", fact: "Pietro Ferrero created the first version of Nutella in 1946 to stretch cocoa supplies with hazelnuts." },
  { name: "GARNIER", category: "Beauty", fact: "Chemist Alfred Amour Garnier launched the brand in 1904 with a hair lotion using plant extracts." },
  { name: "HERSHEY", category: "Food", fact: "Milton Hershey sold his caramel company to fund what became the world's largest chocolate factory." },
  { name: "HYUNDAI", category: "Automotive", fact: "Means modernity in Korean; the company was founded in 1947 and built its first car in 1968." },
  { name: "JACUZZI", category: "Home Wellness", fact: "Candido Jacuzzi invented the whirlpool pump in the 1950s to soothe his son's arthritis." },
  { name: "KELLOGG", category: "Food", fact: "Will Keith Kellogg accidentally discovered corn flakes in 1894 when cooked wheat was left out overnight." },
  { name: "LACOSTE", category: "Fashion", fact: "Tennis champion René Lacoste designed the polo shirt in 1926 to wear on court instead of long sleeves." },
  { name: "MIRINDA", category: "Beverage", fact: "Launched by PepsiCo as a fruit-flavoured soft drink; the name has no known meaning — it was simply trademarked." },
  { name: "NETFLIX", category: "Media", fact: "It began as a DVD-by-mail service before streaming." },
  { name: "PAMPERS", category: "Personal Care", fact: "Launched by Procter & Gamble in 1961 after a company researcher hand-sewed the first prototype." },
  { name: "PANDORA", category: "Jewellery", fact: "Founded in Copenhagen in 1982 by a goldsmith couple who imported jewellery from Thailand." },
  { name: "PERRIER", category: "Beverage", fact: "The water was bottled at a French spring since 1863; the Perrier name came from a buyer in 1898." },
  { name: "PHILIPS", category: "Electronics", fact: "Gerard Philips founded the company in Eindhoven in 1891 in a corrugated iron shed." },
  { name: "PIONEER", category: "Electronics", fact: "Founded in Tokyo in 1938 by Nozomu Matsumoto, who repaired speakers in his home." },
  { name: "PORSCHE", category: "Automotive", fact: "Ferdinand Porsche designed the Volkswagen Beetle before launching his own sports-car brand in 1948." },
  { name: "RAKUTEN", category: "Internet", fact: "Means optimism in Japanese; founded in 1997 as an online marketplace in a Tokyo apartment." },
  { name: "RITUALS", category: "Beauty", fact: "Founded in Amsterdam in 2000, inspired by ancient Eastern wellness traditions." },
  { name: "RYANAIR", category: "Airlines", fact: "Launched in 1984 as a tiny Irish airline with one 15-seat turboprop plane on a single route." },
  { name: "SAMSUNG", category: "Electronics", fact: "Means three stars in Korean — founder Lee Byung-chul chose stars to symbolise strength and eternity." },
  { name: "SHOPIFY", category: "Technology", fact: "It grew out of an online snowboard shop." },
  { name: "SIEMENS", category: "Industrial", fact: "Werner von Siemens built the first long-distance telegraph line in Europe in 1848." },
  { name: "SPOTIFY", category: "Media", fact: "Daniel Ek and Martin Lorentzon founded it in 2006 to provide a better legal alternative to piracy." },
  { name: "TOSHIBA", category: "Electronics", fact: "Formed in 1939 from a merger of Tokyo Denki and Shibaura Seisakusho, combining their names." },
  { name: "TWITTER", category: "Internet", fact: "The founders settled on Twitter after searching for words that evoked a brief burst of trivial information." },
  { name: "VERIZON", category: "Telecom", fact: "A blend of veritas (Latin: truth) and horizon — coined when Bell Atlantic and GTE merged in 2000." },

  // 8 letters
  { name: "BANDCAMP", category: "Media", fact: "Founded in 2008 to let independent artists sell music directly to fans without label intermediaries." },
  { name: "BARCLAYS", category: "Finance", fact: "Named after James Barclay, one of the Quaker goldsmiths who co-founded the bank in 1736." },
  { name: "BROADCOM", category: "Technology", fact: "Name comes from broadband and communication; it designs chips used in almost every Wi-Fi router." },
  { name: "BURBERRY", category: "Fashion", fact: "Thomas Burburry opened a draper's shop in Basingstoke in 1856 and invented gabardine fabric." },
  { name: "CITIBANK", category: "Finance", fact: "Traces back to City Bank of New York, chartered in 1812 — one of America's oldest banks." },
  { name: "COINBASE", category: "Finance", fact: "Founded in 2012 by Brian Armstrong with an ,50,000 Y Combinator seed cheque." },
  { name: "DELOITTE", category: "Consulting", fact: "Named after William Welch Deloitte, who opened an accounting office in London in 1845." },
  { name: "DISCOVER", category: "Finance", fact: "Launched by Sears in 1985 as the first major no-annual-fee credit card." },
  { name: "DOORDASH", category: "Food", fact: "Started by Stanford students in 2013 after they saw a local macaroon shop struggling with deliveries." },
  { name: "EMIRATES", category: "Airlines", fact: "Launched in 1985 with just two aircraft and ,0 million from the Dubai government." },
  { name: "EVERNOTE", category: "Technology", fact: "Founded in 2004 by Stepan Pachikov and Libin; the elephant logo represents the saying elephants never forget." },
  { name: "FACEBOOK", category: "Internet", fact: "It launched first for Harvard students in 2004." },
  { name: "FANDANGO", category: "Media", fact: "Named after the lively Spanish dance — chosen to convey the excitement of going to the movies." },
  { name: "GILLETTE", category: "Personal Care", fact: "King Camp Gillette invented the safety razor in 1901, with disposable blades to drive repeat purchases." },
  { name: "HALLMARK", category: "Greeting Cards", fact: "Founded in 1910 by Joyce Hall, who started by selling picture postcards from a shoebox." },
  { name: "HEINEKEN", category: "Beverage", fact: "Gerard Adriaan Heineken bought an Amsterdam brewery in 1864 at age 22." },
  { name: "LINKEDIN", category: "Internet", fact: "It launched in 2003, before many later social networks." },
  { name: "MARLBORO", category: "Tobacco", fact: "Originally marketed to women in the 1920s; its rugged cowboy image was introduced in the 1950s." },
  { name: "MARRIOTT", category: "Hospitality", fact: "J. Willard Marriott opened a root-beer stand in Washington DC in 1927, which became a restaurant chain." },
  { name: "MERCEDES", category: "Automotive", fact: "Named after Mercedes Jellinek, the daughter of an early Daimler customer who sold the cars." },
  { name: "MONDELEZ", category: "Food", fact: "Created in 2012 when Kraft Foods split; the name blends monde and delez, a made-up word for delicious." },
  { name: "MOTOROLA", category: "Electronics", fact: "Founded in 1928 as Galvin Manufacturing; the name Motorola combined motor with the suffix ola." },
  { name: "NINTENDO", category: "Gaming", fact: "It started in 1889 as a playing card company." },
  { name: "QUALCOMM", category: "Technology", fact: "Stands for Quality Communications; it pioneered CDMA technology that underpins modern mobile networks." },
  { name: "RABOBANK", category: "Finance", fact: "Short for Raiffeisen-Boerenleenbank, a Dutch agricultural cooperative bank founded in 1898." },
  { name: "REYNOLDS", category: "Consumer Goods", fact: "R.J. Reynolds launched the RJR tobacco company in North Carolina in 1875 with $7,500 in capital." },
  { name: "SKECHERS", category: "Apparel", fact: "Founded in 1992 in Manhattan Beach, California, originally as a utility footwear company." },
  { name: "SNAPCHAT", category: "Internet", fact: "It was originally called Picaboo." },
  { name: "SOFTBANK", category: "Telecom", fact: "Founded in 1981 in Japan; Son Masayoshi pitched his business plan using a tangerine crate as a desk." },
  { name: "STARLINK", category: "Telecom", fact: "SpaceX's satellite internet service launched its first batch of 60 satellites in 2019." },
  { name: "TELEGRAM", category: "Technology", fact: "Founded by Pavel Durov after he left VKontakte; designed with privacy as the core principle." },
  { name: "UNILEVER", category: "Consumer Goods", fact: "Formed in 1929 by the merger of British soap maker Lever Brothers and Dutch margarine producer Unie." },
  { name: "VODAFONE", category: "Telecom", fact: "Stands for Voice, Data, and Fone; the British company launched the UK's first mobile call in 1985." },
  { name: "WHATSAPP", category: "Technology", fact: "Founded by two ex-Yahoo engineers who wanted a simple status app; Facebook bought it for ,9 billion." },

  // 9 letters
  { name: "ACCENTURE", category: "Consulting", fact: "The name comes from accent on the future." },
  { name: "ANTHROPIC", category: "Technology", fact: "Founded in 2021 by former OpenAI researchers Dario Amodei and Daniela Amodei." },
  { name: "BLACKROCK", category: "Finance", fact: "Founded in 1988 in a single room; it grew to become the world's largest asset manager." },
  { name: "BLOOMBERG", category: "Media", fact: "Michael Bloomberg built the first Bloomberg terminal in 1981 after being fired by Salomon Brothers." },
  { name: "CARREFOUR", category: "Retail", fact: "The name means crossroads in French; the first hypermarket opened near Lyon in 1963." },
  { name: "CHEVROLET", category: "Automotive", fact: "Louis Chevrolet co-founded the brand in 1911, though General Motors bought him out two years later." },
  { name: "FERRAGAMO", category: "Fashion", fact: "Salvatore Ferragamo made shoes for Hollywood stars in the 1920s before returning to Italy to build his empire." },
  { name: "GRAMMARLY", category: "Technology", fact: "Founded in Kyiv in 2009; the company moved its HQ to San Francisco as it scaled globally." },
  { name: "HONEYWELL", category: "Industrial", fact: "Started in 1906 as the Minneapolis Heat Regulator Company before merging with Honeywell Heating Specialty Co." },
  { name: "HOOTSUITE", category: "Technology", fact: "Founded in Vancouver in 2008; the name comes from a colloquial word for a place of questionable reputation." },
  { name: "INSTAGRAM", category: "Internet", fact: "Kevin Systrom and Mike Krieger built the first version in eight weeks; Facebook bought it for , billion in 18 months." },
  { name: "LULULEMON", category: "Apparel", fact: "Founded in Vancouver in 1998 by Chip Wilson; the name was chosen partly because it is hard to pronounce in Japanese." },
  { name: "MAILCHIMP", category: "Technology", fact: "Started in 2001 as a side project by a web-design firm; the chimp mascot is named Freddie." },
  { name: "MICROSOFT", category: "Technology", fact: "The name blends microcomputer and software." },
  { name: "NORDSTROM", category: "Retail", fact: "John W. Nordstrom opened a Seattle shoe store in 1901 using gold-rush earnings." },
  { name: "OVERSTOCK", category: "Retail", fact: "Founded in 1999 by Patrick Byrne to sell surplus merchandise online when e-commerce was new." },
  { name: "PANASONIC", category: "Electronics", fact: "Originally National; Matsushita adopted Panasonic for the US market in 1955." },
  { name: "PARAMOUNT", category: "Media", fact: "Founded in 1912; its mountain logo was inspired by a Utah mountain near founder William Hodkinson's hometown." },
  { name: "ROBINHOOD", category: "Finance", fact: "Named after the folk hero; the zero-commission brokerage launched in 2014 to democratise investing." },
  { name: "SANTANDER", category: "Finance", fact: "Founded in 1857 in the Spanish port city of Santander to finance trade with Latin America." },
  { name: "STARBUCKS", category: "Food", fact: "Named after the first mate in Moby Dick." },
  { name: "WALGREENS", category: "Retail", fact: "Charles R. Walgreen Sr. opened his first pharmacy in Chicago in 1901 with meticulous soda-fountain service." },
  { name: "WORDPRESS", category: "Technology", fact: "Matt Mullenweg and Mike Little forked an abandoned blogging tool in 2003; it now powers 43% of the web." },
];

// Filter to clean alphabetic 4–9, deduped.
const CLEAN: Brand[] = (() => {
  const seen = new Set<string>();
  const out: Brand[] = [];
  for (const b of BRANDS) {
    const name = b.name.toUpperCase();
    if (!/^[A-Z]+$/.test(name)) continue;
    if (name.length < 4 || name.length > 9) continue;
    if (seen.has(name)) continue;
    seen.add(name);
    const fact = b.fact;
    out.push({ name, category: b.category, fact });
  }
  return out;
})();

export const PUZZLE_BRANDS = CLEAN;
